.TH "KUBERNETES" "1" " kubernetes User Manuals" "Scott Collier" "October 2014"  ""

.SH NAME
.PP
kube\-apiserver \- Provides the API for kubernetes orchestration.

.SH SYNOPSIS
.PP
\fBkubectl\fP [OPTIONS] COMMAND [arg...]

.SH DESCRIPTION
.PP
\fBkubectl\fP is the admin tool used to manage the \fBkubernetes\fP cluser. It is under development.

.SH HISTORY
.PP
October 2014, Originally compiled by Scott Collier (scollier at redhat dot com) based
 on the kubernetes source material and internal work.
